### ISSUE TITLE
NumberTextField problem

### ISSUE THREAD

**Issue by DoVaKeitH** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#1]
For the NumberTextField, in the demo program, we can still input non-numeric value into the textfield like "aaaa" in SettingPane.

Is it a bug? If it is a bug, can I just follow the same output in the demo program?

**Comment by Troublor** [comment]
@ArabelaTso Thanks for pointing out, this is a bug. Your program should not have this issue. You need to make sure users cannot input texts in a number field.

**Comment by ArabelaTso** [comment]
This bug is caused due to obfuscation so I cannot fix it in obfuscate jar :( 
In students' implementation, the NumberTextField should **only accept numbers.**
