### ISSUE TITLE
GamePlayPane startGame

### ISSUE THREAD

**Issue by YuenSC** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#11]
In the startGame of GamePlaypane, I think I need to create something similar to the start() method in JensorMor.java. However, I cannot find any method that can modify the numMoves and currentPlayer field in the fxJesonMor from the GamePlayPane.  Therefore, in order to update those two field, can I create setters for those two fields? or am i missing anything?

**Comment by ArabelaTso** [comment]
Sure, you can add any methods as you like.
