### ISSUE TITLE
About Deserializer

### ISSUE THREAD

**Issue by czhuai** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#13]
About players in Deserializer, are they all random players(computer players)?
About initializing configuration, what is the meaning of "fail"? When will it fail to initialize?

**Comment by ArabelaTso** [comment]
In Deserializer, the type of players doesn't matter, you can initialize them as you like.

About initializing configuration, if the board size is negative, or not a number, the initialization will fail. You may come up with more corner cases.

**Comment by czhuai** [comment]
Got it, thanks.
