### ISSUE TITLE
Asking for Definition of Default value in Grading Scheme

### ISSUE THREAD

**Issue by Xelopie** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#17]
![image](https://user-images.githubusercontent.com/47631876/98022818-0b867200-1e41-11eb-9d9e-c7838c5c0018.png)
In this part for the grading scheme, after we change something for the default settings in settingPane, when we are asked to show the gamePane, which default value should be shown for the text field and button? the default default value (size = 9 and protection = 1) or the changed default value (as changed the settingPane)?

p.s. I mean by the time when we click right into the GamePane, not clicking the "Use Default" button in GamePane

**Comment by ArabelaTso** [comment]
By the time when you click right into the GamePane, the values **not necessarily** update immediately. Just make sure when clicking the "Use Default" button, the values should be updated to the values set in the settingPane.
