### ISSUE TITLE
obfuscated version validation

### ISSUE THREAD

**Issue by DoVaKeitH** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#2]
When I try to run validation on obfuscated version by loading the given file templateJesonMor.txt, there is an error.
Is it a problem due to my computer? or is it a bug?

**Comment by ArabelaTso** [comment]
Hi there, could you please pull it again? Thanks for the reminder, the output format has been changed.

**Comment by ArabelaTso** [comment]
There should be 2 template files under src/main/records.
