### ISSUE TITLE
Code Style Check vs  Intellij Code Analysis

### ISSUE THREAD

**Issue by Xelopie** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#20]
![image](https://user-images.githubusercontent.com/47631876/98081011-58a22c80-1eb1-11eb-8ae7-33a22b421916.png)
The situation here illustrate a problem between the code style checking jar and the Intellij Code Analysis.

The checkstyle.jar suggested us to delete all unused import class. Configuration class is one of the unused import class stated by the jar so I deleted it. Then the @link in JavaDoc about Configuration class method cannot be resolved. Intellij will also notify you that there is a error "Cannot resolve symbol blablablabla....."

So the problem now is: which one should we stick to? The Intellij Code Analysis or the code style checking jar? FYR, the error here I got will not cause any compilation error as it is only related to the JavaDoc but not the code.

**Comment by Xelopie** [comment]
![image](https://user-images.githubusercontent.com/47631876/98086733-1df0c200-1eba-11eb-9ab6-cc4741a108dd.png)
Adding 1 more example to make my question clear.

I don't use any Task class in my entire program. So the checkstyle.jar suggested me to remove the imported Task class. Then the @link to Task is unresolvable

**Comment by ArabelaTso** [comment]
Please feel free to remove JavaDoc to pass the code checker.

**Comment by Xelopie** [comment]
OK
