### ISSUE TITLE
When to play win.mp3

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#21]
It is said in GamaPlayPane checkWinner that "check winner, if winner comes out, then play the win.mp3 and popup window. " Does it mean that no matter who wins, win.mp3 will be played? Or only when the current player wins the win.mp3 will be played? It seems that when the current player use up of his time, lose.mp3 will be played.

**Comment by ArabelaTso** [comment]
> Does it mean that no matter who wins, win.mp3 will be played?

Yes. The winner is not necessarily to be the current player due to the situation of out of available moves.

**Comment by zcmiyano** [comment]
Then when should we play lose.mp3? That's a bit confusing.

**Comment by ArabelaTso** [comment]
If the player has run out of his/her time, then this player will lose, with lose.mp3 plays. But since the countdown timer is a bonus, so basically not every student needs to actually play lose.mp3.

**Comment by zcmiyano** [comment]
OK, got it, thanks.
