### ISSUE TITLE
Grading Scheme - Settings

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#22]
May I ask what does "Input letters (a-zA-z) and symbols in Board size field, no input shows." mean? In the demo those letters can still be typed in the field.

**Comment by ArabelaTso** [comment]
It means when you trying to input letters (a-zA-z) and symbols to NumberTextField, nothing will be shown in the text field. It failed to show in the obfuscated version due to the obfuscation process.
