### ISSUE TITLE
Warning in Setting pane

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#24]
If there are multiple errors found in the setting when save button is clicked, I may report different error from the demo due to the order of checking, will that be acceptable? We only need to report one warning right?

**Comment by ArabelaTso** [comment]
If there are multiple errors, just report the first one that occurs. The order corresponds to the lines' order reading from `.txt` file.

**Comment by zcmiyano** [comment]
I mean in the setting pane there could be multiple errors, how should we deal with this?

**Comment by ArabelaTso** [comment]
In this case, it is ok to report an arbitrary error.
