### ISSUE TITLE
Question about ValidationPane

### ISSUE THREAD

**Issue by lky-bulbasaur** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#26]
In the obfuscated version of PA2, after I validated and finished replaying one game, when I load another file, the `Validate` button becomes enabled again. However, after I validated this another game, the `Replay` button remains disabled.

I would like to know if `ValidationPane` supports the validating and replaying only one game at a time. (i.e. is the user supposed to only load, validate and replay one game before every time they exit to the `MainMenuPane` through the `Return` button?)

Thanks.

**Comment by lky-bulbasaur** [comment]
Also, if someone won in the replay, do we need to display the victory message?

Thanks.

**Comment by ArabelaTso** [comment]
> I would like to know if ValidationPane supports validating and replaying only one game at a time.

Basically, when a loaded record has been validated and replayed, the `Replay` button will be set as disabled. While **when a new record file has been loaded and passed validation**, the `Replay` button can be enabled again.

> if someone won in the replay, do we need to display the victory message?

Not compulsory, but you can do it.
