### ISSUE TITLE
Visual Representation of our Application

### ISSUE THREAD

**Issue by kinshuk-kotecha** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#27]
Does every single detail need to be the same as the obfuscated version? I mean visually? Or is it okay to just have the same functionalities but different aesthetics?

**Comment by kinshuk-kotecha** [comment]
Also, can we import extra packages? And change code in places that are not specified as TODO?

**Comment by ArabelaTso** [comment]
> Does every single detail need to be the same as the obfuscated version? I mean visually? Or is it okay to just have the same functionalities but different aesthetics?

**Unless it is in the GamePlayPane** where you can add buttons to switch players (due to the existence of bonus tasks), otherwise, the visual layout should be **the same** as the obfuscated version.

**Comment by ArabelaTso** [comment]
> can we import extra packages? And change code in places that are not specified as TODO?

Yes.
