### ISSUE TITLE
Validate Record Specifications

### ISSUE THREAD

**Issue by Kit-p** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#28]
Why can the record below pass the validation in the obfuscated program?
What exactly are the things that we need to validate?
It would be great if you can provide a list that will be examined.
```
### FXJesonMor ###

#Game setting
size:9
numMovesProtection:1
centralPlace:(4,4)
numPlayers:2

#Player info
#player1:
name:White; score:9
#player2:
name:Black; score:7

#Move records
player:Red; move:(2,0)->(3,2)
player:Green; move:(5,8)->(5,4)
player:Orange; move:(3,2)->(4,4)
player:Blue; move:(4,8)->(5,6)
player:Yellow; move:(4,4)->(5,6)

END
```

**Comment by lky-bulbasaur** [comment]
I also encountered similar problems so I did some testing. From my observation, the validation algorithm in the obfuscated version seems to ignore texts such as `size:` under `Game setting`, `name:White` under `Player info` and `player:Black` under `Move records`. It seems that that demo program's algorithm only parse the string starting from the k-th character. For example:
- In `size:9`, the algorithm starts parsing from the 6th character to get the board size
- In `player:Black; move:(3,2)->(4,4)`, the algorithm starts parsing from the 20th character to get the move

Although I am not sure if our validation algorithm should follow the exact logic of that in the obfuscated version.

**Comment by ArabelaTso** [comment]
> What exactly are the things that we need to validate?

As states in the code skeleton,      
* Hint:
     *      - validate configuration of game
     *      - whether each move is valid
     *      - whether scores are correct

Validate Game configuration includes:
- board size (positive number, odd, smaller than 26)
- numMovesProtection (positive number)
- whether the central place is correct
- whether the number of player is exactly 2

Validate move is correct: 
- Whether the move breaks the rules of the corresponding piece

Validation score is correct:
- Whether the final scores for two players are correct.

**Comment by ArabelaTso** [comment]
To answer lky-bulbasaur's question:

You can assume the input format is correct. We will only test the above-mentioned values (i.e., configuration of game, movements and final scores) in GUI demo.
