### ISSUE TITLE
Deserializer construct Configuration object

### ISSUE THREAD

**Issue by tcchanan** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#29]
**The Configuration constructor will check the parameter logic (eg odd size, size at least 3, etc), and will throw an error if the requirement is not meet. In Deserializer.java we are required to construct a configuration object when reading the file, so the error will throw immediately.

So when clicking "Load file", the alert will show immediately.
However, in your version, the alert will be displayed after clicking "Validate".

Is it ok to display the error after clicked "Load file"?**

**Comment by JJTam** [comment]
May I ask how did you solve it?

**Comment by kinshuk-kotecha** [comment]
I have the same question as asked by @tcchanan

**Comment by ArabelaTso** [comment]
> Is it ok to display the error after clicked "Load file"?**

No, the error message should show up when the "Validate" button is clicked. 

There are two solutions:
- Store the exceptions when load file, then show up when the "Validate" button is clicked.
- Separate the validation process from the constructor of Configuration.
