### ISSUE TITLE
SettingPane Sound FX button bug

### ISSUE THREAD

**Issue by DoVaKeitH** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#3]
When going to SettingPane for the first time and modifying the field value, once you click Sound FX button, the field value will be resetted. I think this is a bug.

**Comment by ArabelaTso** [comment]
Yes, this is a bug. When clicking the Sound FX button, the value in other fields should not be changed.

**Comment by ArabelaTso** [comment]
This bug has been fixed in the newly-released PA2_obfuscate.jar. Thanks for pointing this out.
