### ISSUE TITLE
Unable to play nor hear CLICK sound

### ISSUE THREAD

**Issue by tywuab** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#30]
I am unable to hear the click sound in the sample program nor in my code after I have implemented onPressed. 
This issue has appeared in a few of our samples.

**Comment by ArabelaTso** [comment]
I checked the obfuscated version, the click sound is played. Do you mean you ONLY cannot hear `click` sound? Or cannot here ALL the sounds?

**Comment by tywuab** [comment]
We can only not hear the click sound, but when we used a linux machine to test it, we can hear the click sound, so it is an issue with the OS?

**Comment by ArabelaTso** [comment]
Which OS you are using? I tried on MacOS, works properly. Anyway, just make sure in your implementation (whatever OS you are using), the sound plays properly when GUI demonstration.

**Comment by Kit-p** [comment]
I have the same issue with Windows 10.
Only the CLICK sound cannot properly be played, both in my implementation and the obfuscated program.

**Comment by tywuab** [comment]
We are using windows, and we can't hear the click sound when we try and use the GUI program

**Comment by ArabelaTso** [comment]
If so, you may use `move.mp3` to replace the `click` sound when the GUI demo.
