### ISSUE TITLE
java.lang.module.FindException

### ISSUE THREAD

**Issue by ywucr** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#31]
I get this error when running the GUIMain. How to fix it? Thanks.
![ddc21a05835f3eb610adb64129fa8ee](https://user-images.githubusercontent.com/56708723/98436736-c9974d80-2118-11eb-93fe-dc67537000e2.png)

**Comment by ArabelaTso** [comment]
Please send me a screenshot of the Project Structure by email.
