### ISSUE TITLE
About negative and illegal input in textField

### ISSUE THREAD

**Issue by leiyi777** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#32]
In the demo, we can input any characters and negative values in the textField so that it can show error messages that "Steps of protection should be greater than or equal to 0." and "Duration of each round should be greater than 0." when we validate the negative numProtectionMove and durationTime.
However, in our project, the textField only allow us to input Integer values, we can not input negative values or any characters so that it may not be able to show the situation that the input is negative and show the corresponding error messages. 
So, do we need to change the property of the textField to make it allow any type of input?

**Comment by ArabelaTso** [comment]
> do we need to change the property of the textField to make it allow any type of input?

No. The input fields in panes belong to the `NumberTextField` class which should ONLY allow the input of numbers. Although the negative value cannot be reached, please show the error message as required.

**Comment by JJTam** [comment]
If I really do allow the user to input characters or other illegal inputs in NumberTextField, but it will pop up the "Incorrect format" alert just like the demo. Will it be any mark deduction?
