### ISSUE TITLE
Do allow illegal inputs in NumberTextField, but pop up alert.

### ISSUE THREAD

**Issue by JJTam** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#35]
If I really do allow the user to input characters or other illegal inputs in NumberTextField, but it will pop up some error message such as "Incorrect format" alert, just like what the demo acts. Will it be any mark deduction?

**Comment by ArabelaTso** [comment]
In this case, it should be fine. 

Just make sure the invalid input (symbols like `+`, `-`, letters, etc.) can be well-handled.
