### ISSUE TITLE
About submission and Smart Player part

### ISSUE THREAD

**Issue by czhuai** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#36]
About submission, the whole project is too large to be uploaded in CASS, may I ask how should I submit it?

About Smart Player part, the grading scheme stated that name the saved records as winRandom[boardSize].txt, I think it should be winRandom[numMovesProtection].txt since we are changing numMovesProtection in the three configurations.

**Comment by czhuai** [comment]
And about use default, do I also need to change the sound setting?

**Comment by ArabelaTso** [comment]
> About submission, the whole project is too large to be uploaded in CASS, may I ask how should I submit it?

I sent an email on Oct 24, which stated:
"Since the entire PA2 project may exceed the maximum space limitation of CASS, so please ONLY compress "src" folder + github_url.txt."

> About Smart Player part, the grading scheme stated that name the saved records as winRandom[boardSize].txt, I think it should be winRandom[numMovesProtection].txt since we are changing numMovesProtection in the three configurations.

You are right. 

> And about use default, do I also need to change the sound setting?

No.

**Comment by czhuai** [comment]
Understand. Thanks for your help.
