### ISSUE TITLE
ValidationPane showErrorMsg

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#38]
/**
     * Pop up window to warn no record has been uploaded.
     * Hint:
     *      - title: Error!
     *      - ContentText: You haven't loaded a record, Please load first.
     */
    private void showErrorMsg()
May I ask when should we use this function? Since the loaded button is disabled if not loaded successfully, I can't come up with a situation that such error could happen.

**Comment by ArabelaTso** [comment]
You are right, showErrorMsg() can only be reached if the "Validate" button is enabled and no record loaded.
