### ISSUE TITLE
DurationTimer

### ISSUE THREAD

**Issue by kinshuk-kotecha** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#39]
DurationTimer class doesn't have any public constructor and none of the important methods are static. So how are we supposed to use it? Can we make the constructor public?

**Comment by kinshuk-kotecha** [comment]
Also, is it necessary to complete all TODO methods even if we don't plan to use them? Like maybe we don't want to use those methods and implement it's functionality somewhere else?
Furthermore, can we change any variable's or method's accessibility or make it static?

**Comment by ArabelaTso** [comment]
> DurationTimer class doesn't have any public constructor and none of the important methods are static.

There is a default constructor. You can either make it public, or use the default constructor directly.

>  is it necessary to complete all TODO methods even if we don't plan to use them?

It is recommended. But you can also implement it somewhere else. 

> can we change any variable's or method's accessibility or make it static?

Yes.

**Comment by kinshuk-kotecha** [comment]
Okay got it. How about changing the implementation of an already defined method?

**Comment by ArabelaTso** [comment]
> How about changing the implementation of an already defined method?

Not recommended, but it is allowed as long as the functions work as expected.
