### ISSUE TITLE
Export Record Format

### ISSUE THREAD

**Issue by Kit-p** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#42]
In the javadoc of Configuration.toString():
```
#player:
name: White, score:14
```
In the template records:
```
#player:
name: White; score:9
```

So, should we use a comma (',') or a semi-colon (';') to separate player name and score?

**Comment by ArabelaTso** [comment]
Sorry about the mistake in JavaDoc, should be `;`. 

The standard format should be like: https://github.com/CastleLab/COMP3021-2020Fall-PA2-Student-Version/blob/main/src/main/records/template_correct_record.txt
