### ISSUE TITLE
GamePane Use Default Players Not Changed

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#5]
In the SettingPane, default players are set to be both computers. However, when use default button is clicked, it won't change back to computers if I change them to human before, and the game will be two human players to play.

**Comment by ArabelaTso** [comment]
It is a bug, for your implementation, the players (computer or human) should also be set as default when the "Use default" button is clicked. Thanks for pointing this out.

**Comment by tcchanan** [comment]
So for the default button, all value should be reset to the value when program start? Or according to setting pane...?

**Comment by Kit-p** [comment]
> 
> 
> It is a bug, for your implementation, the players (computer or human) should also be set as default when the "Use default" button is clicked. Thanks for pointing this out.

I don't think this is a bug. When you click on the buttons, they are actually replacing the "default" values. So, clicking "Use default" should have no effect on the two buttons.
With the current design, I think changing the player types without replacing the "default" values is impossible to implement.
@ArabelaTso Would you please clarify how "Use default" should behave regarding the two buttons?

**Comment by tcchanan** [comment]
> > It is a bug, for your implementation, the players (computer or human) should also be set as default when the "Use default" button is clicked. Thanks for pointing this out.
> 
> I don't think this is a bug. When you click on the buttons, they are actually replacing the "default" values. So, clicking "Use default" should have no effect on the two buttons.
> With the current design, I think changing the player types without replacing the "default" values is impossible to implement.
> @ArabelaTso Would you please clarify how "Use default" should behave regarding the two buttons?

Yes its very confusing...

**Comment by ArabelaTso** [comment]
### [IMPORTANT] Clarification of "Default values"

To answer tcchanan's quesion:

> So for the default button, all value should be reset to the value when program start? Or according to setting pane...?

The default values should be set according to the setting pane. When program starts, there are default values for each configurable variable. While as changing in the settingPane, the default values will be changed accordingly.

To answer Kit-p's question:

> With the current design, I think changing the player types without replacing the "default" values is impossible to implement.
Would you please clarify how "Use default" should behave regarding the two buttons?

It is possible if you maintain a **local** "globalConfiguration" instead of directly changing the default values. And "Use default" should behave not only for the text fields (e.g., board size) but also for these two buttons (player buttons).

Sorry for the confusion caused.

**Comment by Xelopie** [comment]
Can we add some other private instance variable (e.g. private Configuration config;) in order to store the settings in GamePane instead of messing with the globalConfiguration?

**Comment by ArabelaTso** [comment]
Sure.

**Comment by kinshuk-kotecha** [comment]
Currently in the obfuscated version, if I change the player type or the sound fx in the settings, I do not need to press 'save' button. It automatically saves these values as default. Is this the intended behavior?

**Comment by ArabelaTso** [comment]
No. They should only be saved when the "Save" button is clicked. Please refer to the grading specification for the requirement.
