### ISSUE TITLE
Steps of protection & Duration of each round Validation

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#6]
It is said in ViewConfig that:    
   @NotNull
    public static final String MSG_NEG_PROT = "Steps of protection should be positive";
    @NotNull
    public static final String MSG_NEG_DURATION = "Duration of each round should be positive";
However, the actual implementation in the demo is that both of them can be 0.
I think numProtection = 0 should be valid, whereas duration = 0 should not be valid. 
How should we implement this?

**Comment by ArabelaTso** [comment]
Thanks for pointing this out. 

The MSG_NEG_PROT should be "Steps of protection should be greater than or equal to 0."

MSG_NEG_DURATION = "Duration of each round should be greater than 0."

The obfuscated version and ViewConfig have been updated, please pull again, thanks!
