### ISSUE TITLE
ValidationPane after replay end

### ISSUE THREAD

**Issue by DoVaKeitH** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#7]
For the ValidationPane, if the replay is ended and we click the replay button again, nothing will be changed.

Is it a bug?  or when we click the replay button again, we should be able to watch the replay again.

Or the user cannot watch the replay again unless they load the same file again? If this is the case, can I make the replay button being disabled so that this makes more sense

**Comment by ArabelaTso** [comment]
The replay button should be **disabled** after the replay.
