### ISSUE TITLE
Possible Typo in the Grading Scheme

### ISSUE THREAD

**Issue by wytangae** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#8]
The last line in the README.md says that

> Final grade for PA2 = **max**(100, sum of above)

, which means that at least 100 can be obtained by the definition of the **max** function.

Should it be **min** which means that the grade is capped at 100?

**Comment by ArabelaTso** [comment]
Yes, you are right, thanks for pointing it out. Changed accordingly :p
